name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Set up MinGW (i686, x86_64)
        run: sudo apt-get install gcc-mingw-w64-i686 mingw-w64 gcc-mingw-w64-x86-64
      - name: Get commit number
        id: get_commit_number
        run: echo "COMMIT_NUMBER=$(git rev-list --count HEAD)" >> "$GITHUB_OUTPUT"

      - name: Replace placeholder in source file
        run: |
          sed -i 's/COMMIT_NUMBER_PLACEHOLDER/${{ steps.get_commit_number.outputs.COMMIT_NUMBER }}/g' src/ksynth.c
      - name: Build for Linux
        run: |
          make clean
          make
      - name: Upload artifacts (Linux)
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: KSynth Binary (Linux)
          path: |
            out/libksynth.so
      - name: Build for Windows (mingw i686)
        run: |
          make clean
          make WIN32=YES
      - name: Upload artifacts (mingw i686)
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: KSynth Binary (mingw i686)
          path: |
            out/ksynth_x86.dll
      - name: Build for Windows (mingw x86_64)
        run: |
          make clean
          make WIN64=YES
      - name: Upload artifacts (mingw x86_64)
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: KSynth Binary (mingw x86_64)
          path: |
            out/ksynth_x64.dll
